### ISSUE TITLE
issues with small_example\ts_all_call.sql

### ISSUE THREAD

**Issue by qq1037305420** [hettie-d/NORM#13]
Thanks for providing this framework!
I found few issues with file small_example\ts_all_call.sql.
1.  top level schema has a db_prefix: small, generated codes have a prefix small but account. following codes should be norm.small_search_by_ids(array [1,2]) but node.account_search_by_ids
2. at line 176 , function generate_select_by_id_function is named generate_select_by_Id
3. at  line 193 , function  norm_gen.generate_search_generic_function cannot be found in entire repo

**Comment by hettie-d** [comment]
Hello, and thank you for trying NORM! the small_examples is still a work in progress. we intended to show the path from manually written functions to generated functions, but this work is not complete yet. To avoid confusion, I renamed this directory to  "under_construction". All examples from the example directory work as expected.  Thanks again!

**Comment by qq1037305420** [comment]
Thank you! I will try examples within the example directory.
